#!/bin/awk -f

BEGIN {
  #nastaveni separatoru zaznamu na znak < 
  RS="<"
}

/^[Aa] / {
  for (i=2; i<=NF; ++i) {
    if ($i ~ /^href=/) {
      l=substr($i, 6)
      gsub("&quot;", "\"", l)
      gsub("&lt;", "<", l)
      gsub("&gt;", ">", l)
      print l
    }
  }  
}
