#!/bin/bash

vypis_radky () {     #$1=pocet radku, $2=k konec, $3=z zacatek
if [ "$1" -ge "$2" ] ; then
    echo "$( echo "$vstup" | head -n $2 | tail -n $(( $2 - $3 + 1 )) )"
  else   # vypise se cely soubor od m-tyho radky
    echo "$( echo "$vstup" | tail -n $(( $1 - $3 + 1)) )"
  fi
}


if [ "$1" == "-l" ] || [ "$1" == "-lines" ]; then
  if [ $# -eq 2 ]; then vstup="$( cat )" 
  elif [ ! -f "$3" ]; then vstup="$( cat )" #kdyz bude spatna cesta 
  else  vstup=$( cat $3 )
  fi

  z=$( echo "$2" | cut -d "-" -f1)  # z $2 se precte M
  k=$( echo "$2" | cut -d "-" -f2)  # z $2 se precte N 

  radky=$( echo "$vstup" | wc -l )

  vypis_radky $radky $k $z


elif [ "$1" == "-f" ] || [ "$1" == "-fraction" ]; then
  if [ $# -eq 3 ]; then vstup="$( cat )" 
  elif [ ! -f "$4" ]; then vstup="$( cat )" #kdyz bude spatna cesta 
  else  vstup=$( cat $4 )
  fi

  radky=$( echo "$vstup" | wc -l )

  z=$( echo "$2" | cut -d "/" -f1)
  zz=$( echo "$2" | cut -d "/" -f2)
  z=$(( $radky * $z / "$zz" )) #zacatek,expr bere dolni cast

  k=$( echo "$3" | cut -d "/" -f1)
  kk=$( echo "$3" | cut -d "/" -f2)
  k=$(( ($radky * $k + "$kk" - 1) / "$kk" )) #konec, +$kk-1 kvuli zaokr. nahoru
  
  vypis_radky $radky $k $z


elif [ "$1" == "-p" ] || [ "$1" == "-part" ]; then
  if [ $# -eq 2 ]; then vstup="$( cat )" 
  elif [ ! -f "$3" ]; then vstup="$( cat )" #kdyz bude spatna cesta 
  else  vstup=$( cat $3 )
  fi 

  a=$( echo "$2" | cut -d "/" -f1 )
  b=$( echo "$2" | cut -d "/" -f2 )
  radky=$( echo "$vstup" | wc -l )
 
  if [ $(( $radky % $b )) == "0" ];  then
    cast=$(( "$radky" / $b ))
    zbytek=0 
  else
    cast=$(( "$radky" / ($b - 1) ))
    zbytek=$(( $radky  - $b * $cast ))
  fi 

  vypis_radky $radky $(( $cast * $a ))  $(( ($a - 1) * $cast + 1 ))


fi
